package io.github.onedash.linguacpp;

/** Languages supported by the native all-language model. Ordinals are native language IDs. */
public enum Language {
    AFRIKAANS, ALBANIAN, ARABIC, ARMENIAN, AZERBAIJANI, BASQUE, BELARUSIAN, BENGALI,
    BOKMAL, BOSNIAN, BULGARIAN, CATALAN, CHINESE, CROATIAN, CZECH, DANISH, DUTCH,
    ENGLISH, ESPERANTO, ESTONIAN, FINNISH, FRENCH, GANDA, GEORGIAN, GERMAN, GREEK,
    GUJARATI, HEBREW, HINDI, HUNGARIAN, ICELANDIC, INDONESIAN, IRISH, ITALIAN,
    JAPANESE, KAZAKH, KOREAN, LATIN, LATVIAN, LITHUANIAN, MACEDONIAN, MALAY, MAORI,
    MARATHI, MONGOLIAN, NYNORSK, PERSIAN, POLISH, PORTUGUESE, PUNJABI, ROMANIAN,
    RUSSIAN, SERBIAN, SHONA, SLOVAK, SLOVENE, SOMALI, SOTHO, SPANISH, SWAHILI,
    SWEDISH, TAGALOG, TAMIL, TELUGU, THAI, TSONGA, TSWANA, TURKISH, UKRAINIAN, URDU,
    VIETNAMESE, WELSH, XHOSA, YORUBA, ZULU, UNKNOWN
}
